apiVersion: backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "testeeks"
  annotations:
    github.com/project-slug: veecode-bot/cluster_envi
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: terraform-deploy.yml,terraform-destroy.yml
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
  
